// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DeleteOldFunction
 */
export interface DeleteOldFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/delete-old.
 */
export class DeleteOldFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DeleteOldFunctionProps) {
    super(scope, id, {
      description: 'src/delete-old.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/delete-old.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}