// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for TestFunction
 */
export interface TestFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/test.
 */
export class TestFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: TestFunctionProps) {
    super(scope, id, {
      description: 'src/test.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/test.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}